- hosts: Windows
  gather_facts: false

  vars_files:
    - ../../vars/vault.yml
    - ../../vars/vars.yml

  # vars:
  #   Domaine                : Devoteam449.onmicrosoft.com

  #   #8
  #   MFP_Action                                 : "DeleteAttachmentAndUseCustomAlert"
  #   MFP_CustomAlertText                        : "This email contain a malware"
  #   MFP_CustomNotifications                    : False
  #   MFP_EnableExternalSenderAdminNotifications : False
  #   MFP_EnableExternalSenderNotifications      : False
  #   MFP_EnableFileFilter                       : True
  #   MFP_EnableInternalSenderAdminNotifications : False
  #   MFP_EnableInternalSenderNotifications      : True
  #   MFP_Ensure                                 : "Present"
  #   MFP_FileTypes                              : "ace, ani, app, cab, docm, exe, iso, jar, jnlp, reg, scr, vbe, vbs"
  #   MFP_Identity                               : "Anti-malware filtre Policy"
  #   MFP_MakeDefault                            : False
  #   MFP_ZapEnabled                             : True

  #   MFP_Priority             : 0
  #   MFP_SentToMemberOf       : "Devoteam"

  tasks:
    - name: 8 Anti-malware filter policy
      devoteam.o365.win_EXOMalwareFilterPolicy:
        admin_username       : "{{ admin_username }}"
        admin_password       : "{{ admin_password }}"

        Action                                 : "{{ MFP_Action }}"
        CustomAlertText                        : "{{ MFP_CustomAlertText }}"
        CustomNotifications                    : "{{ MFP_CustomNotifications }}"
        EnableExternalSenderAdminNotifications : "{{ MFP_EnableExternalSenderAdminNotifications }}"
        EnableExternalSenderNotifications      : "{{ MFP_EnableExternalSenderNotifications }}"
        EnableFileFilter                       : "{{ MFP_EnableFileFilter }}"
        EnableInternalSenderAdminNotifications : "{{ MFP_EnableInternalSenderAdminNotifications }}"
        EnableInternalSenderNotifications      : "{{ MFP_EnableInternalSenderNotifications }}"
        Ensure                                 : "{{ MFP_Ensure }}"
        FileTypes                              : "{{ MFP_FileTypes }}"
        Identity                               : "{{ MFP_Identity }}"
        MakeDefault                            : "{{ MFP_MakeDefault }}"
        ZapEnabled                             : "{{ MFP_ZapEnabled }}"

    - name: 8 Anti-malware filter policy
      devoteam.o365.win_EXOMalwareFilterRule:
        admin_username       : "{{ admin_username }}"
        admin_password       : "{{ admin_password }}"

        Identity             : "{{ MFP_Identity }}"
        MalwareFilterPolicy  : "{{ MFP_Identity }}"
        Ensure               : "{{ MFP_Ensure }}"
        Priority             : "{{ MFP_Priority }}"
        SentToMemberOf       : "{{ MFP_SentToMemberOf }}@{{ Domaine }}"
